export { lxAccount } from './account.js';
export { lxAdd } from './add.js';
export { lxAddSmall } from './add-small.js';
export { lxAgent } from './agent.js';
export { lxAgentFilled } from './agent-filled.js';
export { lxAlignCenter } from './align-center.js';
export { lxAlignJustified } from './align-justified.js';
export { lxAlignLeft } from './align-left.js';
export { lxAlignRight } from './align-right.js';
export { lxAnalysis } from './analysis.js';
export { lxAppearance } from './appearance.js';
export { lxArchive } from './archive.js';
export { lxArrowDown } from './arrow-down.js';
export { lxArrowLeft } from './arrow-left.js';
export { lxArrowRight } from './arrow-right.js';
export { lxArrowUp } from './arrow-up.js';
export { lxBell } from './bell.js';
export { lxBellDot } from './bell-dot.js';
export { lxBellSlash } from './bell-slash.js';
export { lxBold } from './bold.js';
export { lxBook } from './book.js';
export { lxBrowserExplore } from './browser-explore.js';
export { lxBrowserWeb } from './browser-web.js';
export { lxCalendar } from './calendar.js';
export { lxChat } from './chat.js';
export { lxChatFilled } from './chat-filled.js';
export { lxCheck } from './check.js';
export { lxChevronDown } from './chevron-down.js';
export { lxChevronLeft } from './chevron-left.js';
export { lxChevronRight } from './chevron-right.js';
export { lxChevronUp } from './chevron-up.js';
export { lxClaude } from './claude.js';
export { lxClose } from './close.js';
export { lxCode } from './code.js';
export { lxCommand } from './command.js';
export { lxCopy } from './copy.js';
export { lxCopyCode } from './copy-code.js';
export { lxCsv } from './csv.js';
export { lxCsvFilled } from './csv-filled.js';
export { lxCsvGreen } from './csv-green.js';
export { lxCsvLetter } from './csv-letter.js';
export { lxCsvLetterFilled } from './csv-letter-filled.js';
export { lxCursor } from './cursor.js';
export { lxCursorFilled } from './cursor-filled.js';
export { lxCustomize } from './customize.js';
export { lxCustomizeFilled } from './customize-filled.js';
export { lxDatabase } from './database.js';
export { lxDatabaseFlat } from './database-flat.js';
export { lxDiagnostics } from './diagnostics.js';
export { lxDocx } from './docx.js';
export { lxDocxBlue } from './docx-blue.js';
export { lxDocxFilled } from './docx-filled.js';
export { lxDownload } from './download.js';
export { lxDownloadBox } from './download-box.js';
export { lxDownloadTray } from './download-tray.js';
export { lxEdit } from './edit.js';
export { lxEllipsis } from './ellipsis.js';
export { lxEnter } from './enter.js';
export { lxEraser } from './eraser.js';
export { lxExport } from './export.js';
export { lxExportTray } from './export-tray.js';
export { lxEye } from './eye.js';
export { lxEyeFilled } from './eye-filled.js';
export { lxFileText } from './file-text.js';
export { lxFiles } from './files.js';
export { lxFilter } from './filter.js';
export { lxFold } from './fold.js';
export { lxGear } from './gear.js';
export { lxGitCommit } from './git-commit.js';
export { lxH1 } from './h1.js';
export { lxH2 } from './h2.js';
export { lxH3 } from './h3.js';
export { lxH4 } from './h4.js';
export { lxH5 } from './h5.js';
export { lxImage } from './image.js';
export { lxImageFilled } from './image-filled.js';
export { lxInfo } from './info.js';
export { lxItalics } from './italics.js';
export { lxLayout } from './layout.js';
export { lxLayoutPanel } from './layout-panel.js';
export { lxLayoutPanelOff } from './layout-panel-off.js';
export { lxLayoutSidebarLeft } from './layout-sidebar-left.js';
export { lxLayoutSidebarLeftEmpty } from './layout-sidebar-left-empty.js';
export { lxLayoutSidebarLeftOff } from './layout-sidebar-left-off.js';
export { lxLayoutSidebarLeftOffEmpty } from './layout-sidebar-left-off-empty.js';
export { lxLayoutSidebarRight } from './layout-sidebar-right.js';
export { lxLayoutSidebarRightEmpty } from './layout-sidebar-right-empty.js';
export { lxLayoutSidebarRightOff } from './layout-sidebar-right-off.js';
export { lxLayoutSidebarRightOffEmpty } from './layout-sidebar-right-off-empty.js';
export { lxLegend } from './legend.js';
export { lxLetterB } from './letter-b.js';
export { lxLetterH } from './letter-h.js';
export { lxLetterT } from './letter-t.js';
export { lxLibrary } from './library.js';
export { lxLightning } from './lightning.js';
export { lxLightningFilled } from './lightning-filled.js';
export { lxLinkExternal } from './link-external.js';
export { lxListFilter } from './list-filter.js';
export { lxListUnordered } from './list-unordered.js';
export { lxMenu } from './menu.js';
export { lxModel } from './model.js';
export { lxModelFilled } from './model-filled.js';
export { lxOpenai } from './openai.js';
export { lxOrigin } from './origin.js';
export { lxParameters } from './parameters.js';
export { lxPass } from './pass.js';
export { lxPassFilled } from './pass-filled.js';
export { lxPdf } from './pdf.js';
export { lxPdfFilled } from './pdf-filled.js';
export { lxPdfRed } from './pdf-red.js';
export { lxPinned } from './pinned.js';
export { lxPreview } from './preview.js';
export { lxProjects } from './projects.js';
export { lxProjectsFilled } from './projects-filled.js';
export { lxQuote } from './quote.js';
export { lxQuotes } from './quotes.js';
export { lxRefresh } from './refresh.js';
export { lxRemove } from './remove.js';
export { lxRemoveSmall } from './remove-small.js';
export { lxRss } from './rss.js';
export { lxSave } from './save.js';
export { lxScreenFull } from './screen-full.js';
export { lxScreenNormal } from './screen-normal.js';
export { lxSearch } from './search.js';
export { lxSettings } from './settings.js';
export { lxSplitHorizontal } from './split-horizontal.js';
export { lxSplitPage } from './split-page.js';
export { lxSplitVertical } from './split-vertical.js';
export { lxStar } from './star.js';
export { lxStarFilled } from './star-filled.js';
export { lxSummary } from './summary.js';
export { lxSync } from './sync.js';
export { lxText } from './text.js';
export { lxTranslate } from './translate.js';
export { lxTrash } from './trash.js';
export { lxTrashFlat } from './trash-flat.js';
export { lxTxtLetter } from './txt-letter.js';
export { lxTxtLetterFilled } from './txt-letter-filled.js';
export { lxTypography } from './typography.js';
export { lxUnderline } from './underline.js';
export { lxUnfold } from './unfold.js';
export { lxUnpin } from './unpin.js';
export { lxWarning } from './warning.js';
export { lxWrite } from './write.js';
export { lxXlsGreen } from './xls-green.js';
export { lxXlsLetter } from './xls-letter.js';
export { lxXlsLetterFilled } from './xls-letter-filled.js';
export { lxZoomIn } from './zoom-in.js';
export { lxZoomOut } from './zoom-out.js';
export { lxCustomize as lxBriefcase } from './customize.js';
export { lxCustomizeFilled as lxBriefcaseFilled } from './customize-filled.js';
export { lxLightning as lxFast } from './lightning.js';
export { lxLightningFilled as lxFastFilled } from './lightning-filled.js';
export { lxStar as lxFavorites } from './star.js';
export { lxStarFilled as lxFavoritesFilled } from './star-filled.js';
export { lxLightning as lxFlash } from './lightning.js';
export { lxLightningFilled as lxFlashFilled } from './lightning-filled.js';
export { lxH2 as lxHeading2 } from './h2.js';
export { lxH3 as lxHeading3 } from './h3.js';
export { lxH4 as lxHeading4 } from './h4.js';
export { lxH5 as lxHeading5 } from './h5.js';
export { lxListUnordered as lxListBulleted } from './list-unordered.js';
export { lxAdd as lxPlus } from './add.js';
export { lxAddSmall as lxPlusSmall } from './add-small.js';
export { lxEyeFilled as lxPreviewFilled } from './eye-filled.js';
export { lxEye as lxShow } from './eye.js';
export { lxEyeFilled as lxShowOff } from './eye-filled.js';
export { lxH2 as lxTextH2 } from './h2.js';
export { lxH3 as lxTextH3 } from './h3.js';
export { lxH4 as lxTextH4 } from './h4.js';
export { lxH5 as lxTextH5 } from './h5.js';
export { lxEye as lxView } from './eye.js';
export { lxEyeFilled as lxViewFilled } from './eye-filled.js';
export { lxAddSmall as lxZoomInSmall } from './add-small.js';
export { lxRemoveSmall as lxZoomOutSmall } from './remove-small.js';

export function renderIcon(iconFunction: () => string, container: HTMLElement): SVGElement {
  const div = document.createElement('div');
  div.innerHTML = iconFunction().trim();
  const svgElement = div.firstElementChild as SVGElement;
  container.appendChild(svgElement);
  return svgElement;
}
